services:
  - type: web
    name: translytics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 120 --workers 2"